# Generated by Django 4.1.dev20210924165208 on 2022-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_flashcard_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
    ]
