# Generated by Django 4.1.dev20210924165208 on 2022-03-05 20:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_flashcard_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
