# Generated by Django 4.1.dev20210924165208 on 2022-03-07 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_flashcard_tema_remove_practica_tema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planteamiento', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='practica',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='practica',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='RespuestaCerrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=100)),
                ('id_pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.cerrada')),
            ],
        ),
        migrations.AddField(
            model_name='cerrada',
            name='practica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.practica'),
        ),
        migrations.CreateModel(
            name='Abierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planteamiento', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=100)),
                ('practica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.practica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
