# Generated by Django 4.1.dev20210924165208 on 2022-03-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_cerrada_practica_titulo_practica_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='voto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practica',
            name='voto',
            field=models.IntegerField(default=0),
        ),
    ]
