# Generated by Django 4.1.dev20210924165208 on 2022-03-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_votopract_votoflash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votoflash',
            name='neutro',
        ),
        migrations.RemoveField(
            model_name='votopract',
            name='neutro',
        ),
    ]
