# Generated by Django 4.0.1 on 2022-03-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_respuestacerrada_es_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagenPerfil',
            field=models.ImageField(blank=True, default='planky.png', null=True, upload_to='pfp'),
        ),
    ]
