# Generated by Django 4.0 on 2022-04-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_remove_votopract_id_practica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerrada',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.respuestacerrada'),
        ),
    ]
