# Generated by Django 4.0.1 on 2022-05-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_alter_cerrada_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='practica',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
