# Generated by Django 4.0 on 2022-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_auto_20220815_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerrada',
            name='respuesta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
