# Generated by Django 4.1.dev20210924165208 on 2022-04-15 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0013_remove_votopract_id_practica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoPract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positivo', models.BooleanField(default=False)),
                ('negativo', models.BooleanField(default=False)),
                ('id_practica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.practica')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VotoFlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positivo', models.BooleanField(default=False)),
                ('negativo', models.BooleanField(default=False)),
                ('id_flashcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.flashcard')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
